# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='nl-open-data',
    version='0.1.0',
    description='Datawarehouse of various Dutch open data sources with focus on healthcare and public domain.',
    python_requires='==3.*,>=3.8.0',
    author='Daniel Kapitan',
    author_email='daniel@kapitan.net',
    packages=[
        'nl_open_data', 'nl_open_data.flows', 'nl_open_data.flows.cbs',
        'nl_open_data.flows.kadaster', 'nl_open_data.flows.vektis'
    ],
    package_dir={"": "."},
    package_data={"nl_open_data": ["sql/*.sql"]},
    install_requires=[
        'bokeh==2.*,>=2.1.1', 'click==7.*,>=7.1.2', 'dask==2.*,>=2.21.0',
        'google-auth==1.*,>=1.19.2', 'google-cloud-bigquery==1.*,>=1.26.1',
        'google-cloud-core==1.*,>=1.3.0', 'google-cloud-storage==1.*,>=1.30.0',
        'nimbletl'
    ],
    dependency_links=[
        'git+https://github.com/dkapitan/nimbletl.git#egg=nimbletl'
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0", "flake8==3.*,>=3.8.3",
            "ipykernel==5.*,>=5.3.4", "ipython==7.*,>=7.16.1",
            "pdoc3==0.*,>=0.8.4", "pytest==5.*,>=5.2.0"
        ]
    },
)
